### ISSUE TITLE
DictItem is deprecated in latest scrapy versions

### ISSUE THREAD

**Issue by alexmic** [scrapy-plugins/scrapy-jsonschema#15]
Scrapy logs the following:

```
ScrapyDeprecationWarning: scrapy.item.DictItem is deprecated, please use scrapy.item.Item instead
```

**Comment by BurnzZ** [comment]
Hi @alexmic , yeah this deprecation warning was from `scrapy>=1.8.0` ([change log](https://docs.scrapy.org/en/latest/news.html#id26) specifically from this PR: https://github.com/scrapy/scrapy/pull/3999/files

Thanks for raising this! I'll send out a PR soon.

**Comment by ablewalmsley** [comment]
any updates on this?
